AllCops:
  TargetRubyVersion: 2.3

Layout/CaseIndentation:
  EnforcedStyle: end

# offense count: 4
Layout/EndAlignment:
  Enabled: false

Lint/HandleExceptions:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - "grantinee.gemspec"
    - "spec/**/*"

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/LineLength:
  Max: 100
  Exclude:
    - grantinee.gemspec

Metrics/MethodLength:
  Max: 15

Metrics/ModuleLength:
  Exclude:
    - "spec/**/*"

Security/Eval:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FormatStringToken:
  Enabled: false

Style/StringLiterals:
  Enabled: false
