Layout/CaseIndentation:
  EnforcedStyle: end

# offense count: 4
Layout/EndAlignment:
  Enabled: false

Lint/HandleExceptions:
  Enabled: false
  
Metrics/AbcSize:
  Max: 17

Metrics/AbcSize:
  Max: 17

Metrics/BlockLength:
  Exclude:
    - "grantinee.gemspec"
    - "spec/**/*"

Metrics/LineLength:
  Max: 100
  Exclude:
    - grantinee.gemspec

Metrics/MethodLength:
  Max: 15

Metrics/ModuleLength:
  Exclude:
    - "spec/**/*"

Security/Eval:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FormatStringToken:
  Enabled: false

Style/StringLiterals:
  Enabled: false
