#!/usr/bin/env ruby
# frozen_string_literal: true

require 'bundler/setup'
require 'grantinee'
require 'optparse'

# Autodetect plug-and-play connection
Bundler.require if File.exist? 'Gemfile.lock'

# Logger setup
logger       = Logger.new(STDOUT)
logger.level = Logger::INFO

dsl, engine, executor = Grantinee::CLI.new(ARGV, logger).run!
